### ISSUE TITLE
Consider PyGraphviz and/or Networkx integration

### ISSUE THREAD

**Issue by mapio** [mapio/GraphvizAnim#11]
Ditto

**Comment by ryukinix** [comment]
This would be nice.

**Comment by mapio** [comment]
@ryukinix would you like to volunteer? I'm not an expert of either two packages, which one are you more interested in?

**Comment by ryukinix** [comment]
I can try implement it in the next college vacation (December~January). But I cannot promise anything. I have some knowledge of `networkx`, but not much on PyGraphviz (however I know how use it).

**Comment by mapio** [comment]
Haven't received any news since 2017. Closing by now, I'll be happy to repoen if @ryukinix provides a PR.
