### ISSUE TITLE
Missing how to load existing graph in examples

### ISSUE THREAD

**Issue by HansvdLaan** [mapio/GraphvizAnim#15]
I just came across this project. It looks really good. However, there was one thing blocking me from trying it out. I didn't see in the examples how I could animate an existing graph. Is this not possible or was this feature just not showcased?

**Comment by mapio** [comment]
It is not possible to animate a pre-existing graph: in the context of this package, or according to the approach followed here, the animation is indeed *defined* by the sequence of steps that *build* and/or *modify* the graph.

**Comment by HansvdLaan** [comment]
Is it possible to add such a feature in the future? I'm mostly working with graphs generated by other programs and this would be extremely helpfull.

**Comment by mapio** [comment]
I was probably not clear. This package animations are about adding and removing nodes and arcs. It does not make sense to animate (with this tool) an already existing fixed graph: it's animation will be not animated! I'm not sure to get what you are looking for…

There are many library that will probably will fit better your requirements, give a look at https://github.com/magjac/d3-graphviz for instance: it can render a garph from its dot format and, given a set of graphs, perform a sort of animated transition from one to the other.

This library is about animating the process of building (and modifying) graphs, it will be completely out of its purpose to load graphs generated by other tools.
