### ISSUE TITLE
Locks up in infinite loop when gvanim.render is called

### ISSUE THREAD

**Issue by MarkRdgOx** [mapio/GraphvizAnim#19]
Under Windows, appears to go into an endless loop of spawning new pythonw processes.

**Comment by mapio** [comment]
Can you provide a code snippet that exhibits the problem? Moreover, can you give some more detailed information about OS version, Python interpreter version… 

To fix the problem, I need to be able to reproduce it.

**Comment by javaclll** [comment]
the example code (specifically dfv.py) itself exhibits the problem. upon python dfv.py command, the program goes into an endless loop of spawning new processes as seen in the screenshot below. 

OS: macOS Ventura 13.4.1, Python Interpreter: 3.11

<img width="1530" alt="image" src="https://github.com/mapio/GraphvizAnim/assets/60924861/133e39c8-dfc8-4a90-b62f-909eb463496e">


<img width="732" alt="image" src="https://github.com/mapio/GraphvizAnim/assets/60924861/cbbf2309-850e-46ac-a91c-8db91b5921e5">

**Comment by mapio** [comment]
Should be closed by dc8e544
