### ISSUE TITLE
Unlabeled Nodes cannot be removed

### ISSUE THREAD

**Issue by PhyrexianFox** [mapio/GraphvizAnim#4]
Since the label of a node is not set upon creation, RemoveNode fails on `del steps[ -1 ].L[ self.v ]`
For me, adding `steps[ -1 ].L[ self.v ] = self.v` in AddNode essentially fixed the problem, as did changing the RemoveNode-line to `if self.v in steps[ -1 ].L: del steps[ -1 ].L[ self.v ]`. The second fix seems cleaner to me.

**Comment by mapio** [comment]
Thanks @HTCPCP!
