### ISSUE TITLE
Add code for heapsort animation.

### ISSUE THREAD

**Issue by ryneeverett** [mapio/GraphvizAnim#7]
I don't see the heapsort animation code in the examples directory. It would be very helpful.

**Comment by mapio** [comment]
The code is (presently) in https://github.com/mapio/GraphvizAnim-Examples/blob/master/index.ipynb but I plan to merge the two repos (GraphvizAnim and GraphvizAnim-Examples) in this one as soon as possible.

**Comment by ryneeverett** [comment]
Thanks!
